//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MGK.DeviceHelper.Resources.DefaultResources", typeof(DefaultResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regexbrowserrecords.json.
        /// </summary>
        public static string BrowserJsonFile {
            get {
                return ResourceManager.GetString("BrowserJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accoona-AI-Agent.
        /// </summary>
        public static string BrowserNameAccoonaAIAgent {
            get {
                return ResourceManager.GetString("BrowserNameAccoonaAIAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accoona-AI-Agent.
        /// </summary>
        public static string BrowserNameAccoonaAIAgent1 {
            get {
                return ResourceManager.GetString("BrowserNameAccoonaAIAgent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Browser.
        /// </summary>
        public static string BrowserNameAndroidBrowser {
            get {
                return ResourceManager.GetString("BrowserNameAndroidBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppEngine-Google.
        /// </summary>
        public static string BrowserNameAppEngineGoogle {
            get {
                return ResourceManager.GetString("BrowserNameAppEngineGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avant/IEMobile/SlimBrowser/Baidu.
        /// </summary>
        public static string BrowserNameAvantIEMobileSlimBrowserBaidu {
            get {
                return ResourceManager.GetString("BrowserNameAvantIEMobileSlimBrowserBaidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-l-i-t-z-B-O-T.
        /// </summary>
        public static string BrowserNameBlitzBOT {
            get {
                return ResourceManager.GetString("BrowserNameBlitzBOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boitho.com-dc.
        /// </summary>
        public static string BrowserNameBoithoComDc {
            get {
                return ResourceManager.GetString("BrowserNameBoithoComDc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boitho.com-robot.
        /// </summary>
        public static string BrowserNameBoithoComRobot {
            get {
                return ResourceManager.GetString("BrowserNameBoithoComRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btbot.
        /// </summary>
        public static string BrowserNameBtbot {
            get {
                return ResourceManager.GetString("BrowserNameBtbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerberian Drtrs.
        /// </summary>
        public static string BrowserNameCerberianDrtrs {
            get {
                return ResourceManager.GetString("BrowserNameCerberianDrtrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome for Android/iOS.
        /// </summary>
        public static string BrowserNameChromeAndroidiOS {
            get {
                return ResourceManager.GetString("BrowserNameChromeAndroidiOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome/OmniWeb/Arora/Tizen/Nokia.
        /// </summary>
        public static string BrowserNameChromeOmniWebAroraTizenNokia {
            get {
                return ResourceManager.GetString("BrowserNameChromeOmniWebAroraTizenNokia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome WebView.
        /// </summary>
        public static string BrowserNameChromeWebView {
            get {
                return ResourceManager.GetString("BrowserNameChromeWebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium/Flock/RockMelt/Midori/Epiphany/Silk/Skyfire/Bolt/Iron/Iridium/PhantomJS.
        /// </summary>
        public static string BrowserNameChromiumFlockRockMeltMidoriEpiphanySilkSkyfireBoltIronIridiumPhantomJS {
            get {
                return ResourceManager.GetString("BrowserNameChromiumFlockRockMeltMidoriEpiphanySilkSkyfireBoltIronIridiumPhantomJS" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Dragon.
        /// </summary>
        public static string BrowserNameComodoDragon {
            get {
                return ResourceManager.GetString("BrowserNameComodoDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cosmos.
        /// </summary>
        public static string BrowserNameCosmos {
            get {
                return ResourceManager.GetString("BrowserNameCosmos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covario IDS.
        /// </summary>
        public static string BrowserNameCovarioIDS {
            get {
                return ResourceManager.GetString("BrowserNameCovarioIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomainsDB MetaCrawler.
        /// </summary>
        public static string BrowserNameDomainsDBMetaCrawler {
            get {
                return ResourceManager.GetString("BrowserNameDomainsDBMetaCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmeraldShield.com WebBot.
        /// </summary>
        public static string BrowserNameEmeraldShieldComWebBot {
            get {
                return ResourceManager.GetString("BrowserNameEmeraldShieldComWebBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to envolk[ITS]spider.
        /// </summary>
        public static string BrowserNameEnvolkITSspider {
            get {
                return ResourceManager.GetString("BrowserNameEnvolkITSspider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyfeed Spider.
        /// </summary>
        public static string BrowserNameEveryfeedSpider {
            get {
                return ResourceManager.GetString("BrowserNameEveryfeedSpider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook App for iOS.
        /// </summary>
        public static string BrowserNameFacebookAppiOS {
            get {
                return ResourceManager.GetString("BrowserNameFacebookAppiOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAST Enterprise Crawler.
        /// </summary>
        public static string BrowserNameFASTEnterpriseCrawler {
            get {
                return ResourceManager.GetString("BrowserNameFASTEnterpriseCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAST-WebCrawler.
        /// </summary>
        public static string BrowserNameFASTWebCrawler {
            get {
                return ResourceManager.GetString("BrowserNameFASTWebCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDSE robotFDSE robot.
        /// </summary>
        public static string BrowserNameFDSERobot {
            get {
                return ResourceManager.GetString("BrowserNameFDSERobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Fetcher Google.
        /// </summary>
        public static string BrowserNameFeedFetcherGoogle {
            get {
                return ResourceManager.GetString("BrowserNameFeedFetcherGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox for iOS.
        /// </summary>
        public static string BrowserNameFirefoxiOS {
            get {
                return ResourceManager.GetString("BrowserNameFirefoxiOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox/SeaMonkey/K-Meleon/IceCat/IceApe/Firebird/Phoenix.
        /// </summary>
        public static string BrowserNameFirefoxSeaMonkeyKMeleonIceCatIceApeFirebirdPhoenix {
            get {
                return ResourceManager.GetString("BrowserNameFirefoxSeaMonkeyKMeleonIceCatIceApeFirebirdPhoenix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g2crawler.
        /// </summary>
        public static string BrowserNameG2Crawler {
            get {
                return ResourceManager.GetString("BrowserNameG2Crawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genieBot.
        /// </summary>
        public static string BrowserNameGenieBot {
            get {
                return ResourceManager.GetString("BrowserNameGenieBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Googlebot-Image.
        /// </summary>
        public static string BrowserNameGooglebotImage {
            get {
                return ResourceManager.GetString("BrowserNameGooglebotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great News.
        /// </summary>
        public static string BrowserNameGreatNews {
            get {
                return ResourceManager.GetString("BrowserNameGreatNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hl_ftien_spider.
        /// </summary>
        public static string BrowserNameHlFtienSpider {
            get {
                return ResourceManager.GetString("BrowserNameHlFtienSpider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to htdig.
        /// </summary>
        public static string BrowserNameHtdig {
            get {
                return ResourceManager.GetString("BrowserNameHtdig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ia_archiver.
        /// </summary>
        public static string BrowserNameIaArchiver {
            get {
                return ResourceManager.GetString("BrowserNameIaArchiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iaskspider.
        /// </summary>
        public static string BrowserNameIaskspider {
            get {
                return ResourceManager.GetString("BrowserNameIaskspider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCCrawler.
        /// </summary>
        public static string BrowserNameICCrawler {
            get {
                return ResourceManager.GetString("BrowserNameICCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICE Browser.
        /// </summary>
        public static string BrowserNameICEBrowser {
            get {
                return ResourceManager.GetString("BrowserNameICEBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IceDragon/Iceweasel/Camino/Chimera/Fennec/Maemo/Minimo/Conkeror.
        /// </summary>
        public static string BrowserNameIceDragonIceweaselCaminoChimeraFennecMaemoMinimoConkeror {
            get {
                return ResourceManager.GetString("BrowserNameIceDragonIceweaselCaminoChimeraFennecMaemoMinimoConkeror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ichiro.
        /// </summary>
        public static string BrowserNameIchiro {
            get {
                return ResourceManager.GetString("BrowserNameIchiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer 11.
        /// </summary>
        public static string BrowserNameIE11 {
            get {
                return ResourceManager.GetString("BrowserNameIE11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igdeSpyder.
        /// </summary>
        public static string BrowserNameIgdeSpyder {
            get {
                return ResourceManager.GetString("BrowserNameIgdeSpyder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer.
        /// </summary>
        public static string BrowserNameInternetExplorer {
            get {
                return ResourceManager.GetString("BrowserNameInternetExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes.
        /// </summary>
        public static string BrowserNameITunes {
            get {
                return ResourceManager.GetString("BrowserNameITunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaxified Bot.
        /// </summary>
        public static string BrowserNameJaxifiedBot {
            get {
                return ResourceManager.GetString("BrowserNameJaxifiedBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lftp.
        /// </summary>
        public static string BrowserNameLftp {
            get {
                return ResourceManager.GetString("BrowserNameLftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguee Bot.
        /// </summary>
        public static string BrowserNameLingueeBot {
            get {
                return ResourceManager.GetString("BrowserNameLingueeBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Examiner.
        /// </summary>
        public static string BrowserNameLinkExaminer {
            get {
                return ResourceManager.GetString("BrowserNameLinkExaminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links manager.com Bot.
        /// </summary>
        public static string BrowserNameLinksManagerComBot {
            get {
                return ResourceManager.GetString("BrowserNameLinksManagerComBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Valet.
        /// </summary>
        public static string BrowserNameLinkValet {
            get {
                return ResourceManager.GetString("BrowserNameLinkValet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Validity Check.
        /// </summary>
        public static string BrowserNameLinkValidityCheck {
            get {
                return ResourceManager.GetString("BrowserNameLinkValidityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunascape/Maxthon/Netfront/Jasmine/Blazer.
        /// </summary>
        public static string BrowserNameLunascapeMaxthonNetfrontJasmineBlazer {
            get {
                return ResourceManager.GetString("BrowserNameLunascapeMaxthonNetfrontJasmineBlazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.webis.
        /// </summary>
        public static string BrowserNameLWebis {
            get {
                return ResourceManager.GetString("BrowserNameLWebis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lwp-trivial.
        /// </summary>
        public static string BrowserNameLwpTrivial {
            get {
                return ResourceManager.GetString("BrowserNameLwpTrivial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mabontland.
        /// </summary>
        public static string BrowserNameMabontland {
            get {
                return ResourceManager.GetString("BrowserNameMabontland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magpie-crawler.
        /// </summary>
        public static string BrowserNameMagpieCrawler {
            get {
                return ResourceManager.GetString("BrowserNameMagpieCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magpie RSS.
        /// </summary>
        public static string BrowserNameMagpieRSS {
            get {
                return ResourceManager.GetString("BrowserNameMagpieRSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediapartners-Google.
        /// </summary>
        public static string BrowserNameMediapartnersGoogle {
            get {
                return ResourceManager.GetString("BrowserNameMediapartnersGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Edge.
        /// </summary>
        public static string BrowserNameMicrosoftEdge {
            get {
                return ResourceManager.GetString("BrowserNameMicrosoftEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft URL Control.
        /// </summary>
        public static string BrowserNameMicrosoftURLControl {
            get {
                return ResourceManager.GetString("BrowserNameMicrosoftURLControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIUI Browser.
        /// </summary>
        public static string BrowserNameMIUIBrowser {
            get {
                return ResourceManager.GetString("BrowserNameMIUIBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Safari.
        /// </summary>
        public static string BrowserNameMobileSafari {
            get {
                return ResourceManager.GetString("BrowserNameMobileSafari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mogi.
        /// </summary>
        public static string BrowserNameMogi {
            get {
                return ResourceManager.GetString("BrowserNameMogi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mojoo Robot.
        /// </summary>
        public static string BrowserNameMojooRobot {
            get {
                return ResourceManager.GetString("BrowserNameMojooRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning Paper.
        /// </summary>
        public static string BrowserNameMorningPaper {
            get {
                return ResourceManager.GetString("BrowserNameMorningPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msnbot.
        /// </summary>
        public static string BrowserNameMsnbot {
            get {
                return ResourceManager.GetString("BrowserNameMsnbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mxbot.
        /// </summary>
        public static string BrowserNameMxbot {
            get {
                return ResourceManager.GetString("BrowserNameMxbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetSeer Crawler.
        /// </summary>
        public static string BrowserNameNetSeerCrawler {
            get {
                return ResourceManager.GetString("BrowserNameNetSeerCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NF Reader.
        /// </summary>
        public static string BrowserNameNFReader {
            get {
                return ResourceManager.GetString("BrowserNameNFReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG-Search.
        /// </summary>
        public static string BrowserNameNGSearch {
            get {
                return ResourceManager.GetString("BrowserNameNGSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicebot.
        /// </summary>
        public static string BrowserNameNicebot {
            get {
                return ResourceManager.GetString("BrowserNameNicebot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitro PDF.
        /// </summary>
        public static string BrowserNameNitroPDF {
            get {
                return ResourceManager.GetString("BrowserNameNitroPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noxtrumbot.
        /// </summary>
        public static string BrowserNameNoxtrumbot {
            get {
                return ResourceManager.GetString("BrowserNameNoxtrumbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nusearch Spider.
        /// </summary>
        public static string BrowserNameNusearchSpider {
            get {
                return ResourceManager.GetString("BrowserNameNusearchSpider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obot.
        /// </summary>
        public static string BrowserNameObot {
            get {
                return ResourceManager.GetString("BrowserNameObot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oegp.
        /// </summary>
        public static string BrowserNameOegp {
            get {
                return ResourceManager.GetString("BrowserNameOegp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Explorer.
        /// </summary>
        public static string BrowserNameOfflineExplorer {
            get {
                return ResourceManager.GetString("BrowserNameOfflineExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to omgilibot.
        /// </summary>
        public static string BrowserNameOmgilibot {
            get {
                return ResourceManager.GetString("BrowserNameOmgilibot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OmniExplorer_Bot.
        /// </summary>
        public static string BrowserNameOmniExplorerBot {
            get {
                return ResourceManager.GetString("BrowserNameOmniExplorerBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Link Validator.
        /// </summary>
        public static string BrowserNameOnlineLinkValidator {
            get {
                return ResourceManager.GetString("BrowserNameOnlineLinkValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera &gt; 9.80.
        /// </summary>
        public static string BrowserNameOperaGT980 {
            get {
                return ResourceManager.GetString("BrowserNameOperaGT980", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera &lt; 9.80.
        /// </summary>
        public static string BrowserNameOperaLT980 {
            get {
                return ResourceManager.GetString("BrowserNameOperaLT980", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera Mini.
        /// </summary>
        public static string BrowserNameOperaMini {
            get {
                return ResourceManager.GetString("BrowserNameOperaMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera mini on iphone &gt;= 8.0.
        /// </summary>
        public static string BrowserNameOperaMiniIphoneGTE80 {
            get {
                return ResourceManager.GetString("BrowserNameOperaMiniIphoneGTE80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera Mobi/Tablet.
        /// </summary>
        public static string BrowserNameOperaMobiTablet {
            get {
                return ResourceManager.GetString("BrowserNameOperaMobiTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera Webkit.
        /// </summary>
        public static string BrowserNameOperaWebkit {
            get {
                return ResourceManager.GetString("BrowserNameOperaWebkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playstation 3.
        /// </summary>
        public static string BrowserNamePlaystation3 {
            get {
                return ResourceManager.GetString("BrowserNamePlaystation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetFront.
        /// </summary>
        public static string BrowserNamePlaystationPortable {
            get {
                return ResourceManager.GetString("BrowserNamePlaystationPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ploetz + Zeller.
        /// </summary>
        public static string BrowserNamePloetzZeller {
            get {
                return ResourceManager.GetString("BrowserNamePloetzZeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polaris/Lynx/Dillo/iCab/Doris/w3m/NetSurf/Sleipnir.
        /// </summary>
        public static string BrowserNamePolarisLynxDilloiCabDorisw3mNetSurfSleipnir {
            get {
                return ResourceManager.GetString("BrowserNamePolarisLynxDilloiCabDorisw3mNetSurfSleipnir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polybot.
        /// </summary>
        public static string BrowserNamePolybot {
            get {
                return ResourceManager.GetString("BrowserNamePolybot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrowserName{0}.
        /// </summary>
        public static string BrowserNamePrefix {
            get {
                return ResourceManager.GetString("BrowserNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciprocal Link System PRO.
        /// </summary>
        public static string BrowserNameReciprocalLinkSystemPRO {
            get {
                return ResourceManager.GetString("BrowserNameReciprocalLinkSystemPRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REL Link Checker Lite.
        /// </summary>
        public static string BrowserNameRELLinkCheckerLite {
            get {
                return ResourceManager.GetString("BrowserNameRELLinkCheckerLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safari &amp; Safari Mobile.
        /// </summary>
        public static string BrowserNameSafariAndSafariMobile {
            get {
                return ResourceManager.GetString("BrowserNameSafariAndSafariMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safari &lt; 3.0.
        /// </summary>
        public static string BrowserNameSafariLT30 {
            get {
                return ResourceManager.GetString("BrowserNameSafariLT30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsung Browser.
        /// </summary>
        public static string BrowserNameSamsungBrowser {
            get {
                return ResourceManager.GetString("BrowserNameSamsungBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semanticdiscovery.
        /// </summary>
        public static string BrowserNameSemanticDiscovery {
            get {
                return ResourceManager.GetString("BrowserNameSemanticDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensis Web Crawler.
        /// </summary>
        public static string BrowserNameSensisWebCrawler {
            get {
                return ResourceManager.GetString("BrowserNameSensisWebCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEOChat::Bot.
        /// </summary>
        public static string BrowserNameSEOChatBot {
            get {
                return ResourceManager.GetString("BrowserNameSEOChatBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shim-Crawler.
        /// </summary>
        public static string BrowserNameShimCrawler {
            get {
                return ResourceManager.GetString("BrowserNameShimCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoula robot.
        /// </summary>
        public static string BrowserNameShoulaRobot {
            get {
                return ResourceManager.GetString("BrowserNameShoulaRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to silk.
        /// </summary>
        public static string BrowserNameSilk {
            get {
                return ResourceManager.GetString("BrowserNameSilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sogou spider.
        /// </summary>
        public static string BrowserNameSogouSpider {
            get {
                return ResourceManager.GetString("BrowserNameSogouSpider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedy Spider.
        /// </summary>
        public static string BrowserNameSpeedySpider {
            get {
                return ResourceManager.GetString("BrowserNameSpeedySpider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suggybot.
        /// </summary>
        public static string BrowserNameSuggybot {
            get {
                return ResourceManager.GetString("BrowserNameSuggybot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Susie.
        /// </summary>
        public static string BrowserNameSusie {
            get {
                return ResourceManager.GetString("BrowserNameSusie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.CZ robot.
        /// </summary>
        public static string BrowserNameThumbnailCZRobot {
            get {
                return ResourceManager.GetString("BrowserNameThumbnailCZRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to truwoGPS.
        /// </summary>
        public static string BrowserNameTruwoGPS {
            get {
                return ResourceManager.GetString("BrowserNameTruwoGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TweetedTimes Bot.
        /// </summary>
        public static string BrowserNameTweetedTimesBot {
            get {
                return ResourceManager.GetString("BrowserNameTweetedTimesBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Feed Parser.
        /// </summary>
        public static string BrowserNameUniversalFeedParser {
            get {
                return ResourceManager.GetString("BrowserNameUniversalFeedParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated.
        /// </summary>
        public static string BrowserNameUpdated {
            get {
                return ResourceManager.GetString("BrowserNameUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URD-MAGPIE.
        /// </summary>
        public static string BrowserNameURDMAGPIE {
            get {
                return ResourceManager.GetString("BrowserNameURDMAGPIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vivante Link Checker.
        /// </summary>
        public static string BrowserNameVivanteLinkChecker {
            get {
                return ResourceManager.GetString("BrowserNameVivanteLinkChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voyager.
        /// </summary>
        public static string BrowserNameVoyager {
            get {
                return ResourceManager.GetString("BrowserNameVoyager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W3C Checklink.
        /// </summary>
        public static string BrowserNameW3CChecklink {
            get {
                return ResourceManager.GetString("BrowserNameW3CChecklink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webcollage.
        /// </summary>
        public static string BrowserNameWebcollage {
            get {
                return ResourceManager.GetString("BrowserNameWebcollage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Downloader.
        /// </summary>
        public static string BrowserNameWebDownloader {
            get {
                return ResourceManager.GetString("BrowserNameWebDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websquash.com.
        /// </summary>
        public static string BrowserNameWebsquashCom {
            get {
                return ResourceManager.GetString("BrowserNameWebsquashCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wf84.
        /// </summary>
        public static string BrowserNameWf84 {
            get {
                return ResourceManager.GetString("BrowserNameWf84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii Libnup.
        /// </summary>
        public static string BrowserNameWiiLibnup {
            get {
                return ResourceManager.GetString("BrowserNameWiiLibnup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Media Player.
        /// </summary>
        public static string BrowserNameWindowsMediaPlayer {
            get {
                return ResourceManager.GetString("BrowserNameWindowsMediaPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoFindeIch Robot.
        /// </summary>
        public static string BrowserNameWoFindeIchRobot {
            get {
                return ResourceManager.GetString("BrowserNameWoFindeIchRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xaldon_WebSpider.
        /// </summary>
        public static string BrowserNameXaldonWebSpider {
            get {
                return ResourceManager.GetString("BrowserNameXaldonWebSpider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenu Link Sleuth.
        /// </summary>
        public static string BrowserNameXenuLinkSleuth {
            get {
                return ResourceManager.GetString("BrowserNameXenuLinkSleuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yacy.
        /// </summary>
        public static string BrowserNameYacy {
            get {
                return ResourceManager.GetString("BrowserNameYacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YahooSeeker-Testing.
        /// </summary>
        public static string BrowserNameYahooSeekerTesting {
            get {
                return ResourceManager.GetString("BrowserNameYahooSeekerTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo! Slurp.
        /// </summary>
        public static string BrowserNameYahooSlurp {
            get {
                return ResourceManager.GetString("BrowserNameYahooSlurp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo! Slurp China.
        /// </summary>
        public static string BrowserNameYahooSlurpChina {
            get {
                return ResourceManager.GetString("BrowserNameYahooSlurpChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yoogliFetchAgent.
        /// </summary>
        public static string BrowserNameYoogliFetchAgent {
            get {
                return ResourceManager.GetString("BrowserNameYoogliFetchAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 008.
        /// </summary>
        public static string BrowserNameZeroZeroEight {
            get {
                return ResourceManager.GetString("BrowserNameZeroZeroEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 008.
        /// </summary>
        public static string BrowserNameZeroZeroEight1 {
            get {
                return ResourceManager.GetString("BrowserNameZeroZeroEight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zspider.
        /// </summary>
        public static string BrowserNameZspider {
            get {
                return ResourceManager.GetString("BrowserNameZspider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming Console.
        /// </summary>
        public static string DeviceTypeGamingConsole {
            get {
                return ResourceManager.GetString("DeviceTypeGamingConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceType{0}.
        /// </summary>
        public static string DeviceTypePrefix {
            get {
                return ResourceManager.GetString("DeviceTypePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string ForwardSlash {
            get {
                return ResourceManager.GetString("ForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regexosrecords.json.
        /// </summary>
        public static string OSJsonFile {
            get {
                return ResourceManager.GetString("OSJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android/WebOS/Palm/QNX/Bada/RIM/MeeGo/Contiki.
        /// </summary>
        public static string OSNameAndroidWebOSPalmQNXBadaRIMMeeGoContiki {
            get {
                return ResourceManager.GetString("OSNameAndroidWebOSPalmQNXBadaRIMMeeGoContiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BB10.
        /// </summary>
        public static string OSNameBlackberry10Default {
            get {
                return ResourceManager.GetString("OSNameBlackberry10Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium OS.
        /// </summary>
        public static string OSNameChromiumOS {
            get {
                return ResourceManager.GetString("OSNameChromiumOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox OS.
        /// </summary>
        public static string OSNameFirefoxOS {
            get {
                return ResourceManager.GetString("OSNameFirefoxOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeBSD/NetBSD/OpenBSD/PC-BSD/DragonFly.
        /// </summary>
        public static string OSNameFreeBSDNetBSDOpenBSDPCBSDDragonFlyHaiku {
            get {
                return ResourceManager.GetString("OSNameFreeBSDNetBSDOpenBSDPCBSDDragonFlyHaiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurd/Linux.
        /// </summary>
        public static string OSNameHurdLinux {
            get {
                return ResourceManager.GetString("OSNameHurdLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joli/Ubuntu/Debian/SUSE/Gentoo/Arch/Slackware/Fedora/Mandriva/CentOS/PCLinuxOS/RedHat/Zenwalk/Linpus.
        /// </summary>
        public static string OSNameJoliUbuntuDebianSUSEGentooArchSlackwareFedoraMandrivaCentOSPCLinuxOSRedHatZenwalkLinpus {
            get {
                return ResourceManager.GetString("OSNameJoliUbuntuDebianSUSEGentooArchSlackwareFedoraMandrivaCentOSPCLinuxOSRedHatZ" +
                        "enwalkLinpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac OS.
        /// </summary>
        public static string OSNameMacOS {
            get {
                return ResourceManager.GetString("OSNameMacOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mageia/VectorLinux.
        /// </summary>
        public static string OSNameMageiaVectorLinux {
            get {
                return ResourceManager.GetString("OSNameMageiaVectorLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo DS.
        /// </summary>
        public static string OSNameNintendoDS {
            get {
                return ResourceManager.GetString("OSNameNintendoDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo/Playstation.
        /// </summary>
        public static string OSNameNintendoPlaystation {
            get {
                return ResourceManager.GetString("OSNameNintendoPlaystation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan9/Minix/BeOS/OS2/AmigaOS/MorphOS/RISCOS/OpenVMS.
        /// </summary>
        public static string OSNamePlan9MinixBeOSOS2AmigaOSMorphOSRISCOSOpenVMS {
            get {
                return ResourceManager.GetString("OSNamePlan9MinixBeOSOS2AmigaOSMorphOSRISCOSOpenVMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellOS.
        /// </summary>
        public static string OSNamePlaystation3 {
            get {
                return ResourceManager.GetString("OSNamePlaystation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSName{0}.
        /// </summary>
        public static string OSNamePrefix {
            get {
                return ResourceManager.GetString("OSNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailfish OS.
        /// </summary>
        public static string OSNameSailfishOS {
            get {
                return ResourceManager.GetString("OSNameSailfishOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 40.
        /// </summary>
        public static string OSNameSeries40 {
            get {
                return ResourceManager.GetString("OSNameSeries40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solaris.
        /// </summary>
        public static string OSNameSolaris {
            get {
                return ResourceManager.GetString("OSNameSolaris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows (iTunes).
        /// </summary>
        public static string OSNameWindowsiTunes {
            get {
                return ResourceManager.GetString("OSNameWindowsiTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Mobile.
        /// </summary>
        public static string OSNameWindowsMobile {
            get {
                return ResourceManager.GetString("OSNameWindowsMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Phone.
        /// </summary>
        public static string OSNameWindowsPhone {
            get {
                return ResourceManager.GetString("OSNameWindowsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows RT.
        /// </summary>
        public static string OSNameWindowsRT {
            get {
                return ResourceManager.GetString("OSNameWindowsRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 WebView.
        /// </summary>
        public static string RegexBrowserNameMatchEvaluatorChromeWebView {
            get {
                return ResourceManager.GetString("RegexBrowserNameMatchEvaluatorChromeWebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.+).
        /// </summary>
        public static string RegexBrowserNamePatternChromeWebView {
            get {
                return ResourceManager.GetString("RegexBrowserNamePatternChromeWebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z]+.
        /// </summary>
        public static string RegexBrowserNamePatternMozilla {
            get {
                return ResourceManager.GetString("RegexBrowserNamePatternMozilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d*.
        /// </summary>
        public static string RegexBrowserPatternMajor {
            get {
                return ResourceManager.GetString("RegexBrowserPatternMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z]+.
        /// </summary>
        public static string RegexOSNamePatternDefault {
            get {
                return ResourceManager.GetString("RegexOSNamePatternDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d+(?:\.\d+)*.
        /// </summary>
        public static string RegexOSNamePatterniOs {
            get {
                return ResourceManager.GetString("RegexOSNamePatterniOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^[a-zA-Z]+).
        /// </summary>
        public static string RegexOSNamePatternWindowsMobile {
            get {
                return ResourceManager.GetString("RegexOSNamePatternWindowsMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^[a-zA-Z]+\s[a-zA-Z]+).
        /// </summary>
        public static string RegexOSNamePatternWindowsPhone {
            get {
                return ResourceManager.GetString("RegexOSNamePatternWindowsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^[a-zA-Z]+\s[a-zA-Z]+).
        /// </summary>
        public static string RegexOSNamePatternWindowsRT {
            get {
                return ResourceManager.GetString("RegexOSNamePatternWindowsRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGK.DeviceHelper.
        /// </summary>
        public static string RootNamespace {
            get {
                return ResourceManager.GetString("RootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.
        /// </summary>
        public static string SafariLt30CommercialVersion1 {
            get {
                return ResourceManager.GetString("SafariLt30CommercialVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.
        /// </summary>
        public static string SafariLt30CommercialVersion3 {
            get {
                return ResourceManager.GetString("SafariLt30CommercialVersion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.
        /// </summary>
        public static string SafariLt30CommercialVersion412 {
            get {
                return ResourceManager.GetString("SafariLt30CommercialVersion412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.2.
        /// </summary>
        public static string SafariLt30CommercialVersion416 {
            get {
                return ResourceManager.GetString("SafariLt30CommercialVersion416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.3.
        /// </summary>
        public static string SafariLt30CommercialVersion417 {
            get {
                return ResourceManager.GetString("SafariLt30CommercialVersion417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.4.
        /// </summary>
        public static string SafariLt30CommercialVersion419 {
            get {
                return ResourceManager.GetString("SafariLt30CommercialVersion419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string SafariLt30CommercialVersion8 {
            get {
                return ResourceManager.GetString("SafariLt30CommercialVersion8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string SafariLt30CommercialVersionUnknown {
            get {
                return ResourceManager.GetString("SafariLt30CommercialVersionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /1.
        /// </summary>
        public static string SafariLt30Version1 {
            get {
                return ResourceManager.GetString("SafariLt30Version1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /3.
        /// </summary>
        public static string SafariLt30Version3 {
            get {
                return ResourceManager.GetString("SafariLt30Version3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /412.
        /// </summary>
        public static string SafariLt30Version412 {
            get {
                return ResourceManager.GetString("SafariLt30Version412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /416.
        /// </summary>
        public static string SafariLt30Version416 {
            get {
                return ResourceManager.GetString("SafariLt30Version416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /417.
        /// </summary>
        public static string SafariLt30Version417 {
            get {
                return ResourceManager.GetString("SafariLt30Version417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /419.
        /// </summary>
        public static string SafariLt30Version419 {
            get {
                return ResourceManager.GetString("SafariLt30Version419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /8.
        /// </summary>
        public static string SafariLt30Version8 {
            get {
                return ResourceManager.GetString("SafariLt30Version8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string SafariLt30VersionUnknown {
            get {
                return ResourceManager.GetString("SafariLt30VersionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        public static string Underscore {
            get {
                return ResourceManager.GetString("Underscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Platform.
        /// </summary>
        public static string UserAgentOriginCloudPlatform {
            get {
                return ResourceManager.GetString("UserAgentOriginCloudPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Client.
        /// </summary>
        public static string UserAgentOriginEmailClient {
            get {
                return ResourceManager.GetString("UserAgentOriginEmailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Collector.
        /// </summary>
        public static string UserAgentOriginEmailCollector {
            get {
                return ResourceManager.GetString("UserAgentOriginEmailCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Reader.
        /// </summary>
        public static string UserAgentOriginFeedReader {
            get {
                return ResourceManager.GetString("UserAgentOriginFeedReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library/Application.
        /// </summary>
        public static string UserAgentOriginLibraryOrApp {
            get {
                return ResourceManager.GetString("UserAgentOriginLibraryOrApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Checker.
        /// </summary>
        public static string UserAgentOriginLinkChecker {
            get {
                return ResourceManager.GetString("UserAgentOriginLinkChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Browser.
        /// </summary>
        public static string UserAgentOriginMobileBrowser {
            get {
                return ResourceManager.GetString("UserAgentOriginMobileBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Browser.
        /// </summary>
        public static string UserAgentOriginOfflineBrowser {
            get {
                return ResourceManager.GetString("UserAgentOriginOfflineBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAgentOrigin{0}.
        /// </summary>
        public static string UserAgentOriginPrefix {
            get {
                return ResourceManager.GetString("UserAgentOriginPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser.
        /// </summary>
        public static string UserAgentOriginWebBrowser {
            get {
                return ResourceManager.GetString("UserAgentOriginWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Crawler.
        /// </summary>
        public static string UserAgentOriginWebCrawler {
            get {
                return ResourceManager.GetString("UserAgentOriginWebCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionPart{0}.
        /// </summary>
        public static string VersionPartPrefix {
            get {
                return ResourceManager.GetString("VersionPartPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision/Build.
        /// </summary>
        public static string VersionPartRevisionOrBuild {
            get {
                return ResourceManager.GetString("VersionPartRevisionOrBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string WhiteSpace {
            get {
                return ResourceManager.GetString("WhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ME.
        /// </summary>
        public static string WindowsCommercialVersion490 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersion490", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RT.
        /// </summary>
        public static string WindowsCommercialVersionARM {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string WindowsCommercialVersionNT100 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 3.11.
        /// </summary>
        public static string WindowsCommercialVersionNT351 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 4.0.
        /// </summary>
        public static string WindowsCommercialVersionNT40 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        public static string WindowsCommercialVersionNT50 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP.
        /// </summary>
        public static string WindowsCommercialVersionNT51 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP.
        /// </summary>
        public static string WindowsCommercialVersionNT52 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista.
        /// </summary>
        public static string WindowsCommercialVersionNT60 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string WindowsCommercialVersionNT61 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string WindowsCommercialVersionNT62 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1.
        /// </summary>
        public static string WindowsCommercialVersionNT63 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string WindowsCommercialVersionNT64 {
            get {
                return ResourceManager.GetString("WindowsCommercialVersionNT64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.90.
        /// </summary>
        public static string WindowsVersion490 {
            get {
                return ResourceManager.GetString("WindowsVersion490", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM.
        /// </summary>
        public static string WindowsVersionARM {
            get {
                return ResourceManager.GetString("WindowsVersionARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 10.0.
        /// </summary>
        public static string WindowsVersionNT100 {
            get {
                return ResourceManager.GetString("WindowsVersionNT100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT3.51.
        /// </summary>
        public static string WindowsVersionNT351 {
            get {
                return ResourceManager.GetString("WindowsVersionNT351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT4.0.
        /// </summary>
        public static string WindowsVersionNT40 {
            get {
                return ResourceManager.GetString("WindowsVersionNT40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 5.0.
        /// </summary>
        public static string WindowsVersionNT50 {
            get {
                return ResourceManager.GetString("WindowsVersionNT50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 5.1.
        /// </summary>
        public static string WindowsVersionNT51 {
            get {
                return ResourceManager.GetString("WindowsVersionNT51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 5.2.
        /// </summary>
        public static string WindowsVersionNT52 {
            get {
                return ResourceManager.GetString("WindowsVersionNT52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 6.0.
        /// </summary>
        public static string WindowsVersionNT60 {
            get {
                return ResourceManager.GetString("WindowsVersionNT60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 6.1.
        /// </summary>
        public static string WindowsVersionNT61 {
            get {
                return ResourceManager.GetString("WindowsVersionNT61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 6.2.
        /// </summary>
        public static string WindowsVersionNT62 {
            get {
                return ResourceManager.GetString("WindowsVersionNT62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 6.3.
        /// </summary>
        public static string WindowsVersionNT63 {
            get {
                return ResourceManager.GetString("WindowsVersionNT63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT 6.4.
        /// </summary>
        public static string WindowsVersionNT64 {
            get {
                return ResourceManager.GetString("WindowsVersionNT64", resourceCulture);
            }
        }
    }
}
